version: '3.8'

services:
  app:
    build: ./backend
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - postgres
      - redis

  webserver:
    image: nginx:latest
    container_name: laravel_web
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  postgres:
    image: postgres:14
    container_name: laravel_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testhub
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: laravel_redis
    restart: unless-stopped
    volumes:
      - redis:/data

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.quasar
    ports:
      - "9000:9000"
    volumes:
      - ./frontend:/app  # Монтируем код хоста в контейнер
      - /app/node_modules  # Анонимный том для node_modules
    environment:
      - VITE_API_URL=http://app:8000/api
    depends_on:
      - app
    command: quasar dev --poll

volumes:
  postgres:
  redis:
  node_modules: